steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build' 
  - '-t' 
  - 'gcr.io/$PROJECT_ID/nodejs-service:main_$SHORT_SHA' 
  - '--label' 
  - 'org.opencontainers.image.revision=$COMMIT_SHA' 
  - '--label' 
  - 'org.opencontainers.image.source=Dockerfile'
  - '-f' 
  - 'Dockerfile' 
  - '.'
images: ['gcr.io/$PROJECT_ID/reflexor:main_$SHORT_SHA']
